package mapper;

import model.Jdproduct;

import java.util.ArrayList;

public interface JdproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    int insert(Jdproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    int insertSelective(Jdproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    Jdproduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Jdproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jdproduct record);

    /**
     *
     * @return
     */
    ArrayList<Jdproduct> query();
}