package mapper;

import com.sun.org.apache.bcel.internal.generic.ARRAYLENGTH;
import model.Jdproduct;
import model.Jdproducttype;
import model.JdproducttypeKey;

import java.util.ArrayList;

public interface JdproducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(JdproducttypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    int insert(Jdproducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    int insertSelective(Jdproducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    Jdproducttype selectByPrimaryKey(JdproducttypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Jdproducttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JDPRODUCTTYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jdproducttype record);

    /**
     *
     * @param id
     * @return
     */
    ArrayList<String> querycolor(String id);
}